version: '3'

services:
  mp-api:
    image: mp-api:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8480:8080"
      - "443:8080"
      - "8080:8080"
    volumes:
      - proyect_data:/data
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

volumes:
  proyect_data:
    driver: local
  